apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  selector:
    app: flaresolverr
  type: ClusterIP  # Solo accesible dentro del cluster
  ports:
    - port: 8191
      targetPort: 8191