apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: network
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          value: "eyJhIjoiOWIxYjNkMjE0MGU0NWU3MjkzYjQxMDUxYWMzMTRmZGMiLCJ0IjoiNDMxNjA3ODAtNmZiZi00OTA5LWFjYzYtZjBkNWIzNDE5YmJjIiwicyI6Ik1XWXdabUU1TmpBdE1qVTVZaTAwT1dWa0xXSmhOV1l0TWpnd1kyUTBZakJsTkRrNSJ9"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi