apiVersion: v1
kind: Secret
metadata:
  name: torbox-secrets
  namespace: downloads
  labels:
    app.kubernetes.io/name: torbox-connector
    # app.kubernetes.io/instance: torbox     # opcional, recomendado con Helm o múltiples despliegues
    # app.kubernetes.io/component: credentials  # opcional, para mejor categorización

type: Opaque

stringData:
  api-key: "0e97d5a8-df5a-4c6f-9bce-11d5816a150f"