apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
  namespace: downloads
type: Opaque
stringData:
  rclone.conf: |
    [GDrive]
    type = drive
    scope = drive
    token = {}
    team_drive = 