apiVersion: v1
kind: Secret
metadata:
  name: torbox-rclone-secret
  namespace: downloads
type: Opaque
stringData:
  # Mira en tu cuenta de Torbox los datos de WebDAV
  # A veces el usuario es "token" y el pass es tu API Key, o son específicos.
  WEBDAV_USER: jmmrcp@gmail.com
  WEBDAV_PASS: wH&SBNVT2TA7^h3Vq^